



version: "3"

tasks:
  migrate:
    aliases:
      - gen
    desc: "Generate code from proto"
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./migrations


